apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: swapsbook-com-tls
spec:
  secretName: swapsbook-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: swapsbook.com
  dnsNames:
    - swapsbook.com
    - www.swapsbook.com